<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NIDAQTester12</RootNamespace>
    <AssemblyName>NIDAQTester12.Core</AssemblyName>
    <Platforms>x64</Platforms>
  </PropertyGroup>
</Project>
